# Generated by Django 5.2.6 on 2026-01-18 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medicament_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant investi en FCFA', max_digits=12)),
                ('taux_interet', models.DecimalField(decimal_places=2, default=10.0, help_text="Taux d'intérêt annuel en pourcentage", max_digits=5)),
                ('duree_jours', models.IntegerField(help_text="Durée de l'investissement en jours")),
                ('date_investissement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_echeance', models.DateField(help_text="Date d'échéance de l'investissement")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='ACTIF', max_length=20)),
                ('description', models.TextField(blank=True, help_text="Description ou motif de l'investissement")),
                ('interets_calcules', models.DecimalField(decimal_places=2, default=0, help_text='Intérêts calculés selon le taux et la durée', max_digits=12)),
                ('montant_total_attendu', models.DecimalField(decimal_places=2, default=0, help_text='Montant total attendu (capital + intérêts)', max_digits=12)),
                ('administrateur', models.ForeignKey(help_text="Administrateur qui effectue l'investissement", on_delete=django.db.models.deletion.PROTECT, related_name='investissements_effectues', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(help_text="Utilisateur qui reçoit l'investissement", on_delete=django.db.models.deletion.PROTECT, related_name='investissements_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investissement',
                'verbose_name_plural': 'Investissements',
                'ordering': ['-date_investissement'],
            },
        ),
    ]
