# Generated by Django 5.2.6 on 2026-01-19 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_investissement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('PHARMACIEN', 'Pharmacien(ne)'), ('ASSISTANT', 'Assistant(e) Pharmacien'), ('PREPARATEUR', 'Préparateur(trice)'), ('VENDEUR', 'Vendeur(euse)'), ('GESTIONNAIRE', 'Gestionnaire de Stock'), ('CAISSIER', 'Caissier(ère)'), ('RESPONSABLE', 'Responsable'), ('DIRECTEUR', 'Directeur(trice)'), ('STAGIAIRE', 'Stagiaire'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Poste/Fonction')),
                ('matricule', models.CharField(help_text="Numéro unique d'identification de l'employé", max_length=20, unique=True, verbose_name='Matricule')),
                ('photo', models.ImageField(blank=True, help_text="Photo professionnelle de l'employé", null=True, upload_to='photos_employes/', verbose_name='Photo')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email_professionnel', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('date_embauche', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'embauche")),
                ('date_creation_carte', models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la carte')),
                ('date_expiration_carte', models.DateField(blank=True, null=True, verbose_name="Date d'expiration de la carte")),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes_employes/', verbose_name='QR Code')),
                ('actif', models.BooleanField(default=True, verbose_name='Carte active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes/Remarques')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte_employe', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': "Carte d'employé",
                'verbose_name_plural': "Cartes d'employés",
                'ordering': ['-date_creation_carte'],
            },
        ),
    ]
