# Generated by Django 5.2.6 on 2026-01-29 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_carteemploye'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'assurance")),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('contact_principal', models.CharField(blank=True, max_length=200, verbose_name='Nom du contact principal')),
                ('taux_remboursement_defaut', models.DecimalField(decimal_places=2, default=80.0, max_digits=5, verbose_name='Taux de remboursement par défaut (%)')),
                ('plafond_annuel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Plafond annuel par assuré')),
                ('delai_paiement', models.IntegerField(default=30, verbose_name='Délai de paiement (jours)')),
                ('date_debut_convention', models.DateField(blank=True, null=True, verbose_name='Date début convention')),
                ('date_fin_convention', models.DateField(blank=True, null=True, verbose_name='Date fin convention')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Assurance',
                'verbose_name_plural': 'Assurances',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Numéro de caisse')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('localisation', models.CharField(blank=True, max_length=100, verbose_name='Localisation')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_installation', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'installation")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
                ('nombre_articles', models.IntegerField(default=0, verbose_name="Nombre d'articles")),
                ('valeur_theorique', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valeur théorique')),
                ('valeur_reelle', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valeur réelle')),
                ('ecart_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Écart de valeur')),
                ('remarques', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.IntegerField(verbose_name='Quantité théorique (système)')),
                ('quantite_reelle', models.IntegerField(verbose_name='Quantité réelle (comptée)')),
                ('ecart', models.IntegerField(verbose_name='Écart')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('valeur_theorique', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valeur théorique')),
                ('valeur_reelle', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valeur réelle')),
                ('ecart_valeur', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Écart de valeur')),
                ('date_comptage', models.DateTimeField(auto_now_add=True, verbose_name='Date du comptage')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('ajustement_effectue', models.BooleanField(default=False, verbose_name='Ajustement effectué')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
            },
        ),
        migrations.CreateModel(
            name='LignePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologie', models.TextField(help_text='Ex: 1 comprimé 3 fois par jour pendant 7 jours', verbose_name='Posologie')),
                ('quantite_prescrite', models.IntegerField(verbose_name='Quantité prescrite')),
                ('quantite_delivree', models.IntegerField(default=0, verbose_name='Quantité délivrée')),
                ('substitution_autorisee', models.BooleanField(default=True, verbose_name='Substitution autorisée (générique)')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
            ],
            options={
                'verbose_name': 'Ligne de prescription',
                'verbose_name_plural': 'Lignes de prescription',
            },
        ),
        migrations.CreateModel(
            name='LotMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=100, verbose_name='Numéro de lot')),
                ('date_fabrication', models.DateField(verbose_name='Date de fabrication')),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('date_reception', models.DateField(default=django.utils.timezone.now, verbose_name='Date de réception')),
                ('quantite_initiale', models.IntegerField(verbose_name='Quantité initiale')),
                ('quantite', models.IntegerField(verbose_name='Quantité actuelle')),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat unitaire")),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente unitaire')),
                ('actif', models.BooleanField(default=True, verbose_name='Lot actif')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Lot de médicament',
                'verbose_name_plural': 'Lots de médicaments',
                'ordering': ['date_expiration', 'date_reception'],
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('specialite', models.CharField(choices=[('GENERALISTE', 'Médecin généraliste'), ('PEDIATRE', 'Pédiatre'), ('CARDIOLOGUE', 'Cardiologue'), ('DERMATOLOGUE', 'Dermatologue'), ('GYNECOLOGUE', 'Gynécologue'), ('ORL', 'ORL'), ('OPHTALMOLOGUE', 'Ophtalmologue'), ('PSYCHIATRE', 'Psychiatre'), ('CHIRURGIEN', 'Chirurgien'), ('AUTRE', 'Autre spécialité')], default='GENERALISTE', max_length=30)),
                ('numero_ordre', models.CharField(max_length=50, unique=True, verbose_name='N° Ordre des médecins')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse_cabinet', models.TextField(blank=True, verbose_name='Adresse du cabinet')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée (réception commande)'), ('SORTIE', 'Sortie (vente)'), ('RETOUR_CLIENT', 'Retour client'), ('RETOUR_FOURNISSEUR', 'Retour fournisseur'), ('PEREMPTION', 'Destruction médicament périmé'), ('CASSE', 'Casse/Perte'), ('INVENTAIRE_PLUS', 'Ajustement inventaire (+)'), ('INVENTAIRE_MOINS', 'Ajustement inventaire (-)'), ('TRANSFERT_SORTIE', 'Transfert vers autre pharmacie'), ('TRANSFERT_ENTREE', 'Réception depuis autre pharmacie'), ('ECHANTILLON', 'Échantillon gratuit'), ('USAGE_INTERNE', 'Usage interne')], max_length=30)),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('quantite_avant', models.IntegerField(verbose_name='Stock avant mouvement')),
                ('quantite_apres', models.IntegerField(verbose_name='Stock après mouvement')),
                ('date_mouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('cout_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût unitaire')),
                ('valeur_totale', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valeur totale')),
                ('reference_document', models.CharField(blank=True, help_text='N° facture, bon de livraison, etc.', max_length=100, verbose_name='Référence document')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordonnance', models.CharField(max_length=50, unique=True, verbose_name='N° Ordonnance')),
                ('date_prescription', models.DateField(verbose_name='Date de prescription')),
                ('date_validite', models.DateField(help_text='Les ordonnances ont une durée de validité limitée', verbose_name='Date de validité')),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIELLE', 'Partiellement délivrée'), ('COMPLETE', 'Complètement délivrée'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('fichier_scan', models.FileField(blank=True, null=True, upload_to='ordonnances/', verbose_name="Scan de l'ordonnance")),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('conserve_jusqu_au', models.DateField(blank=True, help_text='Les ordonnances doivent être conservées légalement', null=True, verbose_name="À conserver jusqu'au")),
            ],
            options={
                'verbose_name': 'Prescription/Ordonnance',
                'verbose_name_plural': 'Prescriptions/Ordonnances',
                'ordering': ['-date_prescription'],
            },
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(verbose_name="Date/Heure d'ouverture")),
                ('date_fermeture', models.DateTimeField(blank=True, null=True, verbose_name='Date/Heure de fermeture')),
                ('fond_caisse_ouverture', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Fond de caisse à l'ouverture")),
                ('fond_caisse_fermeture', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fond de caisse à la fermeture')),
                ('total_especes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total espèces')),
                ('total_cb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total carte bancaire')),
                ('total_mobile_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Mobile Money')),
                ('total_cheque', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total chèques')),
                ('nombre_transactions', models.IntegerField(default=0, verbose_name='Nombre de transactions')),
                ('montant_total_ventes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total des ventes')),
                ('ecart_caisse', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Écart de caisse (manquant/excédent)')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='VenteAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(max_length=50, unique=True, verbose_name='N° Dossier')),
                ('numero_assure', models.CharField(max_length=50, verbose_name='N° Assuré')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('montant_assurance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Part assurance')),
                ('montant_patient', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Part patient')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant remboursé')),
                ('date_soumission', models.DateField(blank=True, null=True, verbose_name='Date de soumission')),
                ('date_reponse', models.DateField(blank=True, null=True, verbose_name='Date de réponse')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de soumission'), ('SOUMIS', "Soumis à l'assurance"), ('ACCEPTE', 'Accepté'), ('ACCEPTE_PARTIEL', 'Accepté partiellement'), ('REFUSE', 'Refusé'), ('PAYE', 'Payé'), ('LITIGE', 'En litige')], default='EN_ATTENTE', max_length=20)),
                ('fichier_facture', models.FileField(blank=True, upload_to='factures_assurance/', verbose_name='Facture')),
                ('fichier_reponse', models.FileField(blank=True, upload_to='reponses_assurance/', verbose_name='Réponse assurance')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif de refus')),
            ],
            options={
                'verbose_name': 'Dossier assurance',
                'verbose_name_plural': 'Dossiers assurance',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_autorise',
            field=models.BooleanField(default=False, verbose_name='Crédit autorisé'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_assure',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Assuré'),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_carte_identite',
            field=models.CharField(blank=True, max_length=50, verbose_name="N° Carte d'identité"),
        ),
        migrations.AddField(
            model_name='client',
            name='plafond_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Plafond de crédit'),
        ),
        migrations.AddField(
            model_name='client',
            name='taux_couverture',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Pourcentage pris en charge par l'assurance", max_digits=5, verbose_name='Taux de couverture (%)'),
        ),
        migrations.AddField(
            model_name='itemvente',
            name='remise_ligne',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise sur la ligne'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='classification',
            field=models.CharField(choices=[('LIBRE', 'Vente libre'), ('ORDONNANCE', 'Ordonnance obligatoire'), ('STUPEFIANT', 'Stupéfiant'), ('PSYCHOTROPE', 'Psychotrope')], default='LIBRE', max_length=20, verbose_name='Classification réglementaire'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='code_cip',
            field=models.CharField(blank=True, help_text='Code Identifiant de Présentation', max_length=20, verbose_name='Code CIP'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='dci',
            field=models.CharField(blank=True, max_length=200, verbose_name='DCI (Dénomination Commune Internationale)'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(blank=True, help_text='Ex: 500mg, 10%, 100UI/ml', max_length=100, verbose_name='Dosage/Concentration'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='forme_galenique',
            field=models.CharField(choices=[('COMPRIME', 'Comprimé'), ('GELULE', 'Gélule'), ('SIROP', 'Sirop'), ('SUSPENSION', 'Suspension'), ('SOLUTION', 'Solution'), ('INJECTABLE', 'Injectable'), ('POMMADE', 'Pommade'), ('CREME', 'Crème'), ('GEL', 'Gel'), ('SUPPOSITOIRE', 'Suppositoire'), ('OVULE', 'Ovule'), ('COLLYRE', 'Collyre'), ('AEROSOL', 'Aérosol'), ('POUDRE', 'Poudre'), ('CAPSULE', 'Capsule'), ('PATCH', 'Patch'), ('AUTRE', 'Autre')], default='COMPRIME', max_length=20, verbose_name='Forme galénique'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='liste_stupefiant',
            field=models.CharField(blank=True, choices=[('', 'Non applicable'), ('I', 'Liste I'), ('II', 'Liste II'), ('III', 'Liste III'), ('IV', 'Liste IV')], max_length=10, verbose_name='Liste stupéfiants/psychotropes'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='marge_max',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Marge maximale (%)'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='marge_min',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Marge minimale (%)'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='numero_amm',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° AMM (Autorisation de Mise sur le Marché)'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='pays_origine',
            field=models.CharField(blank=True, max_length=100, verbose_name="Pays d'origine"),
        ),
        migrations.AddField(
            model_name='medicament',
            name='prescription_obligatoire',
            field=models.BooleanField(default=False, verbose_name='Prescription obligatoire'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='prix_achat_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HT"),
        ),
        migrations.AddField(
            model_name='medicament',
            name='tva_taux',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux TVA (%)'),
        ),
        migrations.AddField(
            model_name='vente',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance (crédit)"),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant restant dû'),
        ),
        migrations.AddField(
            model_name='vente',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='N° Facture'),
        ),
        migrations.AddField(
            model_name='vente',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise accordée'),
        ),
        migrations.AddField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='VALIDEE', max_length=20),
        ),
        migrations.AddField(
            model_name='vente',
            name='type_vente',
            field=models.CharField(choices=[('COMPTANT', 'Comptant'), ('CREDIT', 'Crédit'), ('TIERS_PAYANT', 'Tiers payant (assurance)')], default='COMPTANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='date_expiration',
            field=models.DateField(verbose_name="Date d'expiration (lot principal)"),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom commercial'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='numero_lot',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro de lot principal'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente TTC'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='quantite_stock',
            field=models.IntegerField(default=0, verbose_name='Quantité totale en stock'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='methode_paiement',
            field=models.CharField(choices=[('ESPECE', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE', 'Mobile Money'), ('CHEQUE', 'Chèque'), ('MIXTE', 'Paiement mixte')], default='ESPECE', max_length=10),
        ),
        migrations.AlterField(
            model_name='vente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total'),
        ),
        migrations.AddIndex(
            model_name='medicament',
            index=models.Index(fields=['nom'], name='pharmacy_me_nom_1547f3_idx'),
        ),
        migrations.AddIndex(
            model_name='medicament',
            index=models.Index(fields=['dci'], name='pharmacy_me_dci_ec3639_idx'),
        ),
        migrations.AddIndex(
            model_name='medicament',
            index=models.Index(fields=['code_barre'], name='pharmacy_me_code_ba_39be20_idx'),
        ),
        migrations.AddIndex(
            model_name='medicament',
            index=models.Index(fields=['classification'], name='pharmacy_me_classif_b11103_idx'),
        ),
        migrations.AddField(
            model_name='client',
            name='assurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='pharmacy.assurance', verbose_name='Assurance'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nom', 'prenom'], name='pharmacy_cl_nom_b4898a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['telephone'], name='pharmacy_cl_telepho_b3750e_idx'),
        ),
        migrations.AddField(
            model_name='vente',
            name='caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='pharmacy.caisse', verbose_name='Caisse'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='valideur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='compteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_inventaire', to=settings.AUTH_USER_MODEL, verbose_name='Compté par'),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='inventaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacy.inventaire'),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='pharmacy.medicament'),
        ),
        migrations.AddField(
            model_name='ligneprescription',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='pharmacy.medicament'),
        ),
        migrations.AddField(
            model_name='lotmedicament',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='pharmacy.commande', verbose_name="Commande d'origine"),
        ),
        migrations.AddField(
            model_name='lotmedicament',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='pharmacy.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='lotmedicament',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacy.medicament'),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='pharmacy.lotmedicament'),
        ),
        migrations.AddField(
            model_name='itemvente',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='pharmacy.lotmedicament', verbose_name='Lot'),
        ),
        migrations.AddIndex(
            model_name='medecin',
            index=models.Index(fields=['nom', 'prenom'], name='pharmacy_me_nom_1d27a9_idx'),
        ),
        migrations.AddIndex(
            model_name='medecin',
            index=models.Index(fields=['numero_ordre'], name='pharmacy_me_numero__33898b_idx'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='pharmacy.commande'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pharmacy.lotmedicament'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pharmacy.medicament'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='pharmacy.vente'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='pharmacy.medecin'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='pharmacy.client', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='receptionniste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_receptionnees', to=settings.AUTH_USER_MODEL, verbose_name='Réceptionné par'),
        ),
        migrations.AddField(
            model_name='ligneprescription',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacy.prescription'),
        ),
        migrations.AddField(
            model_name='vente',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='pharmacy.prescription', verbose_name='Ordonnance'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pharmacy.caisse'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='caissier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Caissier'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_caisse_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
        migrations.AddField(
            model_name='vente',
            name='session_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='pharmacy.sessioncaisse'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['-date_vente'], name='pharmacy_ve_date_ve_f3558b_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['numero_facture'], name='pharmacy_ve_numero__f58ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['statut'], name='pharmacy_ve_statut_2ed0a6_idx'),
        ),
        migrations.AddField(
            model_name='venteassurance',
            name='assurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='pharmacy.assurance'),
        ),
        migrations.AddField(
            model_name='venteassurance',
            name='vente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_assurance', to='pharmacy.vente'),
        ),
        migrations.AddIndex(
            model_name='lotmedicament',
            index=models.Index(fields=['date_expiration'], name='pharmacy_lo_date_ex_9e3320_idx'),
        ),
        migrations.AddIndex(
            model_name='lotmedicament',
            index=models.Index(fields=['numero_lot'], name='pharmacy_lo_numero__34849d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lotmedicament',
            unique_together={('medicament', 'numero_lot', 'fournisseur')},
        ),
        migrations.AlterUniqueTogether(
            name='ligneinventaire',
            unique_together={('inventaire', 'lot')},
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['-date_mouvement'], name='pharmacy_mo_date_mo_a46034_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='pharmacy_mo_type_mo_0ffbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['numero_ordonnance'], name='pharmacy_pr_numero__788491_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['-date_prescription'], name='pharmacy_pr_date_pr_25178e_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioncaisse',
            index=models.Index(fields=['-date_ouverture'], name='pharmacy_se_date_ou_387b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioncaisse',
            index=models.Index(fields=['caissier'], name='pharmacy_se_caissie_60aee0_idx'),
        ),
        migrations.AddIndex(
            model_name='venteassurance',
            index=models.Index(fields=['numero_dossier'], name='pharmacy_ve_numero__4216cd_idx'),
        ),
        migrations.AddIndex(
            model_name='venteassurance',
            index=models.Index(fields=['statut'], name='pharmacy_ve_statut_155d27_idx'),
        ),
    ]
